version: '3.7'

services:
  bot:
    build: .
    environment:
      PYTHONPATH: "/bots/SpotifyBot"
    command: >
      sh -c "ls
             cd ./src/bot
             python bot.py"

  auth:
    build: .
    ports:
      - "80:80"
    environment:
      PYTHONPATH: "/bots/SpotifyBot"
    command: >
      sh -c "ls
             cd ./src/auth_service
             python auth.py"

  refresh:
    build: .
    environment:
      PYTHONPATH: "/bots/SpotifyBot"
    command: >
      sh -c "ls
             cd ./src/refresh_service
             python service.py"

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'share_music'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    ports:
      - '3306:3306'
    volumes:
      - ./docker_volumes/mysql-data:/var/lib/mysql
      - ./sql_init_scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volumes/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "maxmemory-policy volatile-ttl" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all &*" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all &*" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true